#服务端口
server:
  port: 9527
#服务名称
spring:
  application:
    name: api-gateway-server01
#配置SpringCloudGateway路由
  cloud:
    gateway:
      routes:  #配置路由：路由id,路由到微服务的uri,断言(路由规则)
        - id: order-service
          #uri: http://localhost:8081 #目标微服务请求地址
          #动态路由 在微服务中，微服务提供者不可能只有一台机器，所以不能把地址写死，就需要动态路由
          uri: lb://order-service # 路由的目标地址，lb就是负载均衡，后面跟服务名称
          predicates:
            - Path=/order/**         #路由规则   Path：路径匹配条件

#注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true #使用地址注册


